# Generated by Django 4.1 on 2023-04-24 18:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SuperAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SDJ Test', max_length=60)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('date_of_birth', models.DateField()),
                ('mobile', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits is allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=20)),
                ('role', models.CharField(default='', max_length=200)),
                ('position', models.CharField(default='', max_length=200)),
                ('date_of_program', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('superAttribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.superattribute')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('ranking', models.CharField(choices=[('L', 'Likely'), ('SL', 'Somewhat Likely'), ('SU', 'Somewhat Unlikely'), ('U', 'Unlikely')], max_length=20)),
                ('scenario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='User_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eq', models.IntegerField(default=0)),
                ('influencing', models.IntegerField(default=0)),
                ('communication', models.IntegerField(default=0)),
                ('collaboration', models.IntegerField(default=0)),
                ('problem_solving', models.IntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user')),
            ],
            options={
                'unique_together': {('test', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Test_Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.scenario')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.test')),
            ],
            options={
                'unique_together': {('test', 'scenario')},
            },
        ),
        migrations.CreateModel(
            name='Scenario_Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.attribute')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.scenario')),
            ],
            options={
                'unique_together': {('scenario', 'attribute')},
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('L', 'Likely'), ('SL', 'Somewhat Likely'), ('SU', 'Somewhat Unlikely'), ('U', 'Unlikely')], max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.answer')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user')),
            ],
            options={
                'unique_together': {('user', 'test', 'answer')},
            },
        ),
    ]
